#!/usr/bin/perl

### BEGIN INIT INFO
# Provides:             selenium
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Selenium Server
### END INIT INFO

use warnings;
use strict;
use Daemon::Control;

$ENV{'DISPLAY'} = 'localhost:1.0';

Daemon::Control->new({
    name        => 'Selenium Server',
    lsb_start   => '',
    lsb_stop    => '',
    lsb_sdesc   => 'Selenium Server',
    lsb_desc    => 'Selenium Server Standalone Daemon',
    path        => '/etc/init.d/selenium',
    program     => '/usr/bin/java',
    program_args => [
        '-jar',
        '/var/lib/selenium-server-standalone.jar',
        '-log',
        '/var/log/selenium.log',
        '-trustAllSSLCertificates',
    ],
    pid_file    => '/var/run/selenium.pid',
    fork        => 2,
})->run;
